# Generated by Django 5.0.3 on 2024-03-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_people_you_may_know'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendshipResquest',
            new_name='FriendshipRequest',
        ),
    ]
